import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navigation />

      <div className="pt-20 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <div className="mb-8">
            <h1 className="text-3xl lg:text-4xl font-bold text-gray-900 mb-4">Site Terms and Conditions</h1>
            <p className="text-lg text-gray-600">Effective Date: July 1, 2025</p>
          </div>

          <div className="prose prose-lg max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Introduction</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                Wytmode Cloud Private Limited ("Company", "we", "our", or "us"), headquartered in Bengaluru, India, is
                the legal owner and operator of the PlanInsta application. We are fully committed to safeguarding the
                privacy of our users and ensuring transparency in how we manage their personal and business data.
              </p>
              <p className="text-gray-700 leading-relaxed">
                These Terms and Conditions govern your use of the PlanInsta platform operated by Wytmode Cloud Private
                Limited. By registering for, accessing, or using any part of the PlanInsta application, you agree to
                comply with and be legally bound by these terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Eligibility and Access</h2>
              <ul className="space-y-2 text-gray-700">
                <li>
                  • You must be at least 18 years of age or have the legal consent of a parent or guardian to use this
                  platform.
                </li>
                <li>
                  • We reserve the right to deny access or terminate accounts found violating age or eligibility
                  restrictions.
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">2. User Account Responsibilities</h2>
              <ul className="space-y-2 text-gray-700">
                <li>• You are solely responsible for maintaining the confidentiality of your login credentials.</li>
                <li>
                  • You agree not to share your account with others. Unauthorized account sharing or access is a
                  violation and may result in termination.
                </li>
                <li>• You are responsible for all activities conducted under your account.</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">3. Plan Generation and Usage Limits</h2>
              <ul className="space-y-2 text-gray-700">
                <li>
                  • PlanInsta provides access to a set number of business plan generations based on the pricing plan
                  purchased (e.g., 3 plans for Starter, 10 plans for Professional).
                </li>
                <li>
                  • Usage beyond the defined plan limits will require an upgrade or additional purchase. Unused plans do
                  not carry over to future cycles.
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Intellectual Property Rights</h2>
              <ul className="space-y-2 text-gray-700">
                <li>
                  • The PlanInsta platform, including its design, source code, features, and content, is the
                  intellectual property of Wytmode Cloud Pvt. Ltd. All rights are reserved.
                </li>
                <li>
                  • Business plans generated by users are their intellectual property. We do not claim ownership over
                  your content.
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Termination of Services</h2>
              <p className="text-gray-700 leading-relaxed">
                We reserve the right to suspend or permanently terminate any user account that violates our terms,
                engages in illegal activities, abuses the AI system, or exploits vulnerabilities in the service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Disclaimers and Limitation of Liability</h2>
              <ul className="space-y-2 text-gray-700">
                <li>
                  • PlanInsta provides AI-generated business plans. These should not be interpreted as financial, legal,
                  or business advice. Users must validate all content before using it in formal submissions.
                </li>
                <li>
                  • We are not liable for any business losses, inaccuracies, or negative outcomes resulting from
                  reliance on AI-generated content.
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Modifications to Terms</h2>
              <ul className="space-y-2 text-gray-700">
                <li>
                  • These terms may be updated from time to time. Continued use of the platform constitutes acceptance
                  of the most recent version.
                </li>
                <li>• It is your responsibility to review these terms periodically.</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Contact Information</h2>
              <p className="text-gray-700 leading-relaxed mb-2">For legal or usage-related queries, contact:</p>
              <div className="bg-gray-50 rounded-2xl p-6">
                <p className="text-gray-700">
                  <strong>Email:</strong> support@wytmode.com
                </p>
              </div>
            </section>

            <section className="bg-orange-50 rounded-2xl p-6 border-l-4 border-orange-500">
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Company Information</h3>
              <p className="text-gray-700 mb-2">
                <strong>Wytmode Cloud Private Limited</strong>
              </p>
              
              <p className="text-gray-700 mb-2">
                <strong>Registered Address:</strong>
                <br />
                #63, H Colony, 2nd Main, Indira Nagar
                <br />
                1st Stage, Bengaluru (KA - IND) 560038
              </p>
              <p className="text-gray-700 mb-2">
                <strong>Email:</strong> support@wytmode.com
                <br />
                <strong>Phone:</strong> (+91) 8884557972 / 8277276944
              </p>
              <p className="text-gray-700">
                <strong>Website:</strong> www.wytmode.com
              </p>
            </section>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  )
}
